# Generated by Django 5.1.4 on 2025-01-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(upload_to="products/images/"),
        ),
        migrations.AlterField(
            model_name="products",
            name="tags",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
