# Generated by Django 5.1.4 on 2025-01-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_products_image_alter_products_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.URLField(),
        ),
    ]
