# Generated by Django 5.1.4 on 2025-01-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_products_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
