# Generated by Django 5.1.4 on 2025-01-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_products_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
