# Generated by Django 5.1.4 on 2025-01-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_products_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="slug",
        ),
    ]
